version: '2'
services:
  backend:
    image: ronaldgcr/api-dev-node:0.0.1
    ports:
      - 80:3000    
    volumes:
      - ./app/:/app
    environment:
      LC_ALL: en_US.UTF-8
    command: npm start 
  test:
    image: $IMAGE_DEPLOY
    volumes:
      - ./app:/app
    depends_on:
      - backend
    command: npm test