version: '2'
services:

  backend:
    image: $IMAGE_DEPLOY_TEST
    ports:
      - 80:3000    
    container_name: $PROJECT_NAME
    volumes:
      - ./app/:/app
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LC_ALL: en_US.UTF-8
    command: npm start 
  mysql:
      image: mysql:5.5
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: reservation
      ports:
        - 3307:3306
      volumes:
        - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      command: mysqld --sql_mode=""
  test:
    image: $IMAGE_DEPLOY_TEST
    ports:
      - 80:3000    
    container_name: $PROJECT_NAME
    volumes:
      - ./app/:/app
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LC_ALL: en_US.UTF-8
    command: npm test 